### ISSUE TITLE
About BiasNet

### ISSUE THREAD

**Issue by czwhczwh75** [deepcs233/TIN#2]
hi~
I am confused when i reading temporal_interlace.py code in this line.
I think 4 is a magic number where in the paper it's T, which means temporal frames;

https://github.com/deepcs233/TIN/blob/336b8cb0233c87d6a9ccf7775f30ab247710edf2/ops/temporal_interlace.py#L94

Please tell me where I'm wrong.

**Comment by deepcs233** [comment]
It has similar performance, you can set it to T. 4 is just a stable param for it here.
