### ISSUE TITLE
Incorrect comparison in your aaai paper

### ISSUE THREAD

**Issue by YuqiHUO** [deepcs233/TIN#3]
Thank you for the great work! When I was reading your paper, I find that in Table 1, you claimed that TSM could only get 43.4, 44.8, and 46.8 under three settings, while TIN outperforms TSM all by 2-3%(45.8, 47.0 and 49.6). But in TSM's origin paper, the number is far higher:
TSM gets 45.6, 47.2, and 49.7 under sth-sth v1 validation top1's setting, while TIN only gets 45.8, 47.0, and 49.6, so there is almost no difference while TIN has slightly more flops/video.
I whether which version is correct.

**Comment by deepcs233** [comment]
The performance of TSM which I compared with is from https://arxiv.org/abs/1811.08383v1. They have revised their performance after we submitted the AAAI-2020 camera ready.
